server.port=8091
spring.application.name=svc-catalogo

# Redis config
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/db_catg
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.initialization-fail-timeout=60000

logging.level.com.biblioteca=INFO
