events {
    worker_connections 1024;
}

http {
    upstream catalogo_svc {
        server svc-catalogo:8091;
    }

    upstream prestamos_svc {
        server svc-prestamos:8092;
    }

    upstream miembros_svc {
        server svc-miembros:8093;
    }

    server {
        listen 8080;
        server_name localhost;

        # svc-catalogo → /libros y /catalogo/health
        location /libros {
            proxy_pass http://catalogo_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /catalogo {
            proxy_pass http://catalogo_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # svc-prestamos → /prestamos
        location /prestamos {
            proxy_pass http://prestamos_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # svc-miembros → /miembros
        location /miembros {
            proxy_pass http://miembros_svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
